export const [
  POSICAO_VEICULOS_1,
  POSICAO_VEICULOS_2,
  POSICAO_VEICULOS_3,
  SEARCH_POSICAO_LINHA,
  SEARCH_POSICAO_GARAGEM,
  INFO_LINHAS_1
] = [
    'POSICAO_VEICULOS_1',
    'POSICAO_VEICULOS_2',
    'POSICAO_VEICULOS_3',
  'SEARCH_POSICAO_LINHA',
  'SEARCH_POSICAO_GARAGEM',
  'INFO_LINHAS_1'
]